/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MTMS;

import java.io.*;
/**
 *
 * @author hguo87
 * comments by Yuan He
 * 
 * This the database setting frame, user can set the database information,
 * after the use set successfully,the frame will dispose and go back to login
 * frame
 */

public class Setup_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Setup_GUI
     */
    
    public MTMS_Login fromMain = null;
    
    public Setup_GUI() {
        initComponents();
    }
    
    public String DBAccount = "root";
    public String DBPwd = "";
    public String DBName = "MTMS";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbxDBName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbxDBAccount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbxDBPwd = new javax.swing.JPasswordField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tbxError = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Database Name:");

        tbxDBName.setText("MTMS");

        jLabel2.setText("User Account:");

        tbxDBAccount.setText("root");

        jLabel3.setText("Password:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tbxError.setBackground(new java.awt.Color(240, 240, 240));
        tbxError.setForeground(new java.awt.Color(0, 153, 51));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, tbxError)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(btnOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel1)
                                .add(jLabel2)
                                .add(jLabel3)))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(tbxDBName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .add(tbxDBAccount)
                                .add(tbxDBPwd))
                            .add(btnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(tbxDBName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tbxDBAccount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(tbxDBPwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnOK)
                    .add(btnCancel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tbxError, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //dispose current frame and go to login 
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        if (fromMain == null) return;
        fromMain.setVisible(true);
        fromMain.dbgui = null;
        fromMain = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    
    /*
     * set the database with the information from the input, if success, the 
     * frame will dispose and go back to previous frame 
    */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (tbxDBName.getText().replace("'", "").trim().equals(""))
        {
            tbxError.setText("Empty database name.");
            return;
        }
        if (tbxDBAccount.getText().replace("'", "").trim().equals(""))
        {
            tbxError.setText("Empty user account.");
            return;
        }
        DBName = tbxDBName.getText().replace("'", "").trim();
        DBAccount = tbxDBAccount.getText().replace("'", "").trim();
        DBPwd = tbxDBPwd.getText().replace("'", "\\'").trim();
        
       //test database connection
        Test_Controller TC = new Test_Controller("localhost",DBName, DBAccount, DBPwd);
        TC.getConnection();
        if (!TC.Is_Connected)
        {
            tbxError.setText("Invalid id/password or connection failed.");
            return;
        }
        
        //create a DB.txt to save the database information
        OutputStreamWriter writer = null;
        File f = new File("./Data");

        if (!f.exists()) {
            try
            {
                f.mkdirs();
            }
            catch(Throwable e){
            }
        }
        
        f = new File("./Data/DB.txt");

        if (!f.exists()) {
            try {
                f.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        try {
            writer = new OutputStreamWriter(new FileOutputStream("./Data/DB.txt"));
            writer.write("DBName:"+ DBName +"\r\nDBAccount:"+DBAccount+"\r\nDBPwd:"+DBPwd+"\r\n");
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        if (fromMain == null) return;
                
        fromMain.DBName = DBName;
        fromMain.DBAccount = DBAccount;
        fromMain.DBPwd = DBPwd;
        fromMain.setVisible(true);
        fromMain.dbgui = null;
        
        fromMain = null;
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    
    // Initiate the database information to input ui
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tbxDBName.setText(DBName);
        tbxDBAccount.setText(DBAccount);
        tbxDBPwd.setText(DBPwd);
        btnOK.getRootPane().setDefaultButton(btnOK);
    }//GEN-LAST:event_formWindowOpened

    //dispose the current frame and go back to main frame
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (fromMain == null) return;
        fromMain.setVisible(true);
        fromMain.dbgui = null;
        fromMain = null;
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setup_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setup_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setup_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setup_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tbxDBAccount;
    private javax.swing.JTextField tbxDBName;
    private javax.swing.JPasswordField tbxDBPwd;
    private javax.swing.JTextField tbxError;
    // End of variables declaration//GEN-END:variables
}
